# Simple shortcuts and magics

In [ ]:
#Установим библиотеку для отрисовки графиков, если её у вас нет
!pip install matplotlib

In [ ]:
#Magic, который пишем чаще всего. Что он делает?
#import numpy
#import matplotlib
#from matplotlib import pylab, mlab, pyplot
#np = numpy
#plt = pyplot
#from IPython.display import display
#from IPython.core.pylabtools import figsize, getfigs
#from pylab import *
#from numpy import *

#и все это 1 строчкой! inline указывает, что вывод графиков будет в ноутбук (подробнее в документации: выбор движка)
%pylab inline

In [ ]:
#Найдите magic, который записывает значение ячейки в файл. Создайте модуль hello.py, импортируйте из него hello_world
def hello_world():
    print("hello")

In [ ]:
#Засеките время выполнения процедуры с помощью magic
def count(start=0, end=10000):
    for _ in range(start, end):
        continue

In [ ]:
#Объедините эту ячейку и ячейку ниже с помощью shortcut
def very_important_function():
    start="end"

In [ ]:
    fucing_cat="change the cell"

In [ ]:
#Исправьте все хождения value в ячейке на name
value="value_1"
value_value="value_value_2"

In [ ]:
#Содержание ячейки, запущенной второй
print()

# Numpy

In [1]:
#Импортируем модуль
import numpy as np

In [12]:
#Создадим всякие массивчики
string_array = np.array(["строка", 5])
float_array = np.array([5., 5])
float_array_2 = np.array([6.])
int_array = np.array([5, 4])
two_dimarray = np.array([[5, 4], [4, 6]])
one_dimarray = np.array([[5, 4], [4]])

In [15]:
#К массивам можно обращаться по 2 индексам. Возможны срезу по нескольким осям
example_list = [[5, 4], [7, 8]]
example_list[:, 1]

TypeError: list indices must be integers or slices, not tuple

In [17]:
example_arr = np.array([[5, 4], [7, 8]])
example_arr[:, 1]

array([4, 8])

In [22]:
#Можно получить параметры массива: тип данных, форму, размерность вдоль оси
two_dimarray = np.array([[5, 4], [4, 6]])
print("Размерность вдоль первой оси: {}".format(len(two_dimarray)))
print("Размерность массива: {}".format(two_dimarray.shape))
print("Тип данных в массиве: {}".format(two_dimarray.dtype))

#Давайте пожмем наш int64 до int8 (преподложим, что знаем ограничение на размер чисел)
import sys
print("Размер исходного массива %d" % sys.getsizeof(two_dimarray))
two_dimarray = two_dimarray.astype(np.int8)
print("Размер массива после преобразования %d" % sys.getsizeof(two_dimarray))

Размерность вдоль первой оси: 2
Размерность массива: (2, 2)
Тип данных в массиве: int64
Размер исходного массива 144
Размер массива после преобразования 116


In [6]:
oneses = np.ones(3)
zeros = np.zeros(4)
print(oneses)
print(zeros)

[1. 1. 1.]
[0. 0. 0. 0.]


In [42]:
def simple_matrix_generator(n):
    #TODO создать единичную матрицу размера n x n в виде numpy array
    return 

In [43]:
assert np.array_equal(simple_matrix_generator(4), np.array([[1., 0., 0., 0.], [0., 1., 0., 0.], [0., 0., 1., 0.], [0., 0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(3), np.array([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]))
assert np.array_equal(simple_matrix_generator(2), np.array([[1., 0.], [0., 1.]]))

AssertionError: 

In [9]:
#Преобразование формы массива 
example = np.array([5, 4, 7, 8])
print(example)
print(example.reshape(2, 2))
print(example.reshape(2, 2).flatten())

[5 4 7 8]
[[5 4]
 [7 8]]
[5 4 7 8]


In [16]:
# Массивы можно по-разному объединять и добавлять элементы
example = np.array([5., 6.])
example = np.append(example, example)
print(example)
example = np.array([[5.], [6.]])
print(np.concatenate((example, example), axis=0))
print(np.concatenate((example, example), axis=1))
print(np.vstack((example, example)))
print(np.hstack((example, example)))

[5. 6. 5. 6.]
[[5.]
 [6.]
 [5.]
 [6.]]
[[5. 5.]
 [6. 6.]]
[[5.]
 [6.]
 [5.]
 [6.]]
[[5. 5.]
 [6. 6.]]


In [19]:
#Над массивами numpy можно производить простейшие математические операции
example = np.array([5, 4, 7, 8])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Multidemensional")
example = np.array([[5, 4], [7, 8]])
print(example / 2)
print(example * 3)
print(example + 32)
print(example - 1)
print(example ** 2)
print("Lessdimensional")
example = np.array([[5, 4], [7, 8]])
sep_arr = np.array([2, 3])
print(example / sep_arr)
print(example * sep_arr)
print(example + sep_arr)
print(example - sep_arr)
print(example ** sep_arr)

[2.5 2.  3.5 4. ]
[15 12 21 24]
[37 36 39 40]
[4 3 6 7]
[25 16 49 64]
Multidemensional
[[2.5 2. ]
 [3.5 4. ]]
[[15 12]
 [21 24]]
[[37 36]
 [39 40]]
[[4 3]
 [6 7]]
[[25 16]
 [49 64]]
Lessdimensional
[[2.5        1.33333333]
 [3.5        2.66666667]]
[[10 12]
 [14 24]]
[[ 7  7]
 [ 9 11]]
[[3 1]
 [5 5]]
[[ 25  64]
 [ 49 512]]


In [20]:
#Можно производить стандартные операции над векторами n-мерного пространства
example = np.array([[5, 4], [7, 8]])
print(example.transpose())

[[5 7]
 [4 8]]


In [44]:
#И снова калькулятор
def calculate(a, b=None, func="+"):
    #TODO Ну мы такое уже писали, кажется, совсем просто
    if func == "+":
        return a + b
    if func == "-":
        return a - b
    if func == "**":
        return a ** b
    if func == "*":
        return a * b
    if func == "/":
        return a / b
    if func == "transpose":
        return a.transpose()
    if func == "increment":
        #TODO увеличвает на 1 ДИАГОНАЛЬНЫЕ элементы, если матрица квадратная, иначе возвращает исходную матрицу
        if a.shape[0] == a.shape[1] and len(a.shape)==2:
            return a + np.identity(a.shape[0])
        return a
    #Примените func ко всем эементам a
    return func(a)

In [ ]:
assert np.array_equal()

In [28]:
#TODO по тесту на каждый метод размерность a не менее 2x2. Применить функции np.sin, np.cos, np.exp, np.square


In [31]:
#Можно считать различные статистикиЮ суммы и другие значения по выбранной оси
example = np.array([[5, 4], [7, 8]])
print(example.sum())
print(example.sum(axis=0))
print(example.sum(axis=1))

#TODO Найти минимум по столбцам, максимум по строкам, среднее значение всей матриц, дисперсию по строкам и аргминимум по строке

24
[12 12]
[ 9 15]


In [34]:
#Методы выбора
example = np.array([[5, 4], [7, 8]])
example[example >= 5]

array([5, 7, 8])

In [35]:
#Просто скалярное произведение
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

In [ ]:
#TODO Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
#A^(T)Ax=A^(T)y
#x=(A^(T)A)^(-1)A^(T)y
#давайте сделаю свою решалку таких уравнений
#HINT: np.linalg...
def solution_finder(A, y):
    return


In [ ]:
#TODO решить систему методом Крамера